encoding: UTF-8

###########
# site.title, site.url, site.author.name

title:   'Mönsterstudion'
path:    /monsterstudion
url:     'https://dacre.github.io/monsterstudion/'
author:
  name:  'dacre'

########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md


safe: true
lsi: false
